### ISSUE TITLE
how to update mongodb 7.0.12

### ISSUE THREAD

**Issue by xjdtd** [vickyphang/ha-mongo-cluster#1]
My dear：
  how to upgrade the mongodb 7.0.12 ？

**Comment by vickyphang** [comment]
@xjdtd to install/upgrade a specific version of mongodb, you can specify the version when create the mongodb replica set. Based on my example, you have to edit file **config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml**:
```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "7.0.12"   #<-- define your desired version of mongodb
[...]
```

If the mongodb already deployed, you can edit the deployed mongodb resourse and specify parameter `spec.version`:
```bash
# List deployed resource
kubectl get MongoDBCommunity --all-namespaces

# Edit desired deployment
kubectl edit MongoDBCommunity <resource-name> --namespace mongodb
```
